### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by shoeffner** [shoeffner/mthesis#1]
- [x] Add correct submission date to `meta.yaml`
- [x] Check references (especially Bibliography itself)
- [x] Check minimal required versions (e.g. C++ Standard, CMake version, etc.)
- [x] Release and tag Version 1.0
- [x] ~Burn~ code to ~CD or~ SD cards
- [x] Write list of possible extensions, features
- [x] Clean up git repositories
- [x] publish repositories
- [x] Check links (especially documentation versions etc.)
